baseURL = "https://www.damiannicholson.com"
languageCode = "en-uk"
title = "Damian Nicholson"
theme = "damian"
metaDataFormat = "toml"
pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsStyle = "monokailight"

[permalinks]
posts = "/:year/:month/:day/:slug"